FROM httpd:latest

# Copier la page index.html dans le dossier par défaut d'Apache
COPY index.html /usr/local/apache2/htdocs/

# Copier un fichier de configuration
COPY httpd.conf /usr/local/apache2/conf/httpd.conf

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]