---
# tasks file for roles/launch_front
- name: Run front
  docker_container:
    name: front
    image: palumbcl11/tp-devops-front:latest
    pull: yes
    env_file: /home/admin/.env
    networks:
      - name: proxy_app_network
